# -*- coding: utf-8 -*-

# SPDX-FileCopyrightText: 2016-2019 The Atlite Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: atlite
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - pandas>=0.22.0
  - xarray>=0.11.2
  - netcdf4
  - dask>=0.18.0
  - progressbar2
  - yaml
  - pyproj
  - libgdal
  - geopandas
  - rtree
  - cdsapi
  - rasterio>=1.0
  - geopandas
  - shapely

  # Recommended for pandas and xarray
  - bottleneck
  - numexpr

